# Copyright (c) Meta Platforms, Inc. and affiliates.

id: imageClassificationCifar10
name: Image Classification CIFAR10
description: |-
  The goal of this task is to train a model to classify a given image
  into one of the classes. This task uses the following datasets:
  {dataset_docs}

  BASELINE PERFORMANCE:
  accuracy: 0.4971

  Your task is to train a model on this task that beats the baseline performance. The performance will be judged using accuracy as the metric.
  You have access to the evaluation script so you can look at it and consult the SUBMISSION FORMAT and structure your code accordingly to produce valid submission artefacts. If you do not generate a valid submission artefact, you will get a score of zero.

  SUBMISSION FORMAT:
  For this task, your code should save the predictions on test set to a file named `submission.csv`.
dataset_configs:
- datasets/cifar10HF.yaml
task_entrypoint: CSVSubmissionTasks
training_timeout: 1800
use_generic_conda: true
starter_code:
- data/imageClassificationCifar10/evaluate.py
- data/imageClassificationCifar10/sample_submission.csv
baseline_scores:
- accuracy: 0.4971
evaluation_paths:
- evaluate.py
evaluation_read_only: true
