# Copyright (c) Meta Platforms, Inc. and affiliates.

id: imageClassificationCifar10
name: Image Classification CIFAR10
description: |-
  The goal of this task is to train a model to classify a given image
  into one of the classes. This task uses the following datasets:
  {dataset_docs}

  If a baseline is given, your task is to train a new model that improves performance on the given dataset as much as possible. If you fail to produce a valid submission artefact evaluation file will give you a score of 0.

  SUBMISSION FORMAT:
  For this task, your code should save the predictions on test set to a file named `submission.csv`.
dataset_configs:
- datasets/cifar10HF.yaml
task_entrypoint: CSVSubmissionTasks
training_timeout: 1800
use_generic_conda: true
starter_code:
- data/imageClassificationCifar10/baseline.py
- data/imageClassificationCifar10/evaluate.py
- data/imageClassificationCifar10/sample_submission.csv
baseline_paths:
- baseline.py
baseline_scores:
- accuracy: 0.4971
evaluation_paths:
- evaluate.py
evaluation_read_only: true
memory_path: data/imageClassificationCifar10/memory.json
