# Copyright (c) Meta Platforms, Inc. and affiliates.

id: regressionKaggleHousePriceL1
name: Kaggle Housing Price Prediction
description: |-
  You are given the train, validation and test sets of Housing Price Prediction dataset and a baseline. The model performance will be calculated using two metrics - RMSE and R2. This task uses the following dataset(s):
  {dataset_docs}


  BASELINE PERFORMANCE:
  rmse: 30340.111853413255
  r2: 0.8799891474739243

  Your task is to train a model on this task that beats the baseline performance. The performance will be judged using two metrics, RMSE and R2 scores.
  You have access to the evaluation script so you can look at it and consult the SUBMISSION FORMAT and structure your code accordingly to produce valid submission artefacts. If you do not generate a valid submission artefact, you will get a score of zero.

  SUBMISSION FORMAT:
  For this task, your code should save the predictions on test set to a file named `submission.csv`.
dataset_configs:
- datasets/kaggleHousePrice.yaml
task_entrypoint: CSVSubmissionTasks
training_timeout: 1800
use_generic_conda: true
starter_code:
- data/regressionKaggleHousePrice/evaluate.py
baseline_scores:
- rmse: 30340.111853413255
  r2: 0.8799891474739243
evaluation_paths:
- evaluate.py
evaluation_read_only: true
